[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:transmission]
command=transmission-daemon
    --foreground
    --config-dir /config/transmission
    --download-dir /downloads
    --port 9091
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10

[program:automaticrss]
command=python /app/main.py
directory=/app
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=20
